program: experiments.end_to_end.end_to_end_experiment
name: 3dprover_novel
description: 3DProver Novel Sweep
project: leandojo_novel_premises

method: grid
metric:
  goal: maximize
  name: Pass@1
parameters:
  tac_model.diversity_config.score_network:
    values: [ false ]
  tac_model.diversity_config.fixed_size:
    values: [ true ]
  tac_model.diversity_config.num_filtered:
    values: [ 32, 16, 8 ]
  exp_config.name:
    values: [ '3d_prover-k${tac_model.diversity_config.num_filtered}' ]

command:
  - ${env}
  - ${interpreter}
  - '-m'
  - ${program}
  - '--config-name=end_to_end/3dprover_novel_premises'
  - ${args_no_hyphens}

