program: experiments.end_to_end.end_to_end_experiment
name: combined_model_sweep
description: Combined Model Sweep
project: minif2f_test

method: grid
metric:
  goal: maximize
  name: Pass@1
parameters:
#  tac_model.diversity_config.p:
#    values: [ 0.5, 0.75 ]
  tac_model.diversity_config.score_network:
    values: [ false ]
  tac_model.diversity_config.fixed_size:
    values: [ true ]
  tac_model.diversity_config.num_filtered:
    values: [ 8, 16, 32 ]
#  tac_model.diversity_config.error_weight:
#    values: [ 0.1, 0.5 ]
  #  tac_model.diversity_config.temperature:
#      values: [ 1, 2 ]
  exp_config.name:
    values: [ 'fixed_combined-k${tac_model.diversity_config.num_filtered}' ]

command:
  - ${env}
  - ${interpreter}
  - '-m'
  - ${program}
  - '--config-name=end_to_end/diversity_tac_model'
  - ${args_no_hyphens}

