model: diversity
ckpt_path: null
num_sampled_tactics: 64

distributed: true
gpu_per_process: 0.225
cpu_per_process: 0.125

gpu_per_diversity: 0.225
cpu_per_diversity: 0.125

diversity_config:
  # transition only:
  #  ckpt_dir: 'runs/minif2f/minif2f_combined.ckpt'

  # combined transition/error/time prediction:
  ckpt_dir: runs/error_pred/combined_transition_model/combined_minif2f_valid.ckpt

  model: 'sean-lamont/leandojo-lean3-reprover-novel-premises'
  max_seq_len: 2000
  num_filtered: 8
  temperature: 1
  p: 0.75

  score_network: true
  error_weight: 0.5
  time_weight: 0.1

  error_only: false
  fixed_size: false

config:
  model_name: sean-lamont/leandojo-lean3-reprover-novel-premises
  #   retriever args
  ret_ckpt_path: runs/retriever_novel_premises.ckpt
  #  indexed_corpus_path: runs/indexed_corpus
  indexed_corpus_path: runs/indexed_corpus_minif2f
  eval_num_retrieved: 100

  lr: 5e-6
  warmup_steps: 200
  length_penalty: 0.0
  num_beams: 64
  max_seq_len: 1300
  gen_config:
    strategy: beam
    length_penalty: 0.0
  # configuration for the eval loop in training (terminates based on live proving performance)
  eval_config:
    eval_num_theorems: 200
    shuffle: false
    timeout: 600
