# @package _global_
defaults:
  - /base/logging_config@_here_
  - /base/exp_config@_here_

exp_config:
  name: dpo_beamsearch
  experiment: dpo_beamsearch

logging_config:
  project: leandojo_dpo
  offline: false

experiment:
  _target_: models.end_to_end.tactic_models.dpo.model.DPOTrainModule
  model_type: 'tac_gen'
  model_name: kaiyuy/leandojo-lean3-tacgen-byt5-small
  lr: 1e-6
  warmup_steps: 150
  beta: 0.99
  max_seq_len: 2300
  gen_config:
    strategy: beam
    length_penalty: 0.0
  #    strategy: sample
  eval_config:
    eval_num_theorems: 200
    shuffle: false
    timeout: 600
  lora_config:
    target_modules: [ 'q', 'k', 'v', 'o', 'wo', 'lm_head' ]
    task_type: "SEQ_2_SEQ_LM"
    r: 16
    lora_alpha: 16
    lora_dropout: 0.01

data_module:
  _target_: models.end_to_end.tactic_models.dpo.datamodule.GoalProvableDataModule
  model_name: kaiyuy/leandojo-lean3-tacgen-byt5-small
  batch_size: 4  # effective_batch_size == batch_size * accumulate_grad_batches * devices
  eval_batch_size: 4
  max_seq_len: 2300
  num_workers: 0
  trace_files: null
#  database: null
#  collection: null

trainer:
  accelerator: gpu
  devices: 2
  precision: bf16-mixed
  strategy:
    _target_: lightning.pytorch.strategies.DeepSpeedStrategy
    stage: 2
    offload_optimizer: false
    cpu_checkpointing: false
    logging_batch_size_per_gpu: 4
  gradient_clip_val: 1.0
  max_steps: 5000000
  val_check_interval: 30000
  callbacks:
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      verbose: true
      save_top_k: 3
      save_last: true
      monitor: Pass@1_val
      mode: max
      dirpath: ${exp_config.directory}/checkpoints
      auto_insert_metric_name: true
      filename: "{epoch}-{step}-{Pass@1_val:.2f}"