seed_everything: 3407  # https://arxiv.org/abs/2109.08203
trainer:
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  strategy:
    class_path: pytorch_lightning.strategies.DeepSpeedStrategy
    init_args:
      stage: 2
      offload_optimizer: false
      cpu_checkpointing: false
      logging_batch_size_per_gpu: 1
  gradient_clip_val: 1.0
  max_steps: 50000000
  val_check_interval: 5000
  limit_val_batches: 1000
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        verbose: true
        save_top_k: 3
        save_last: true
        monitor: winner_preferred
        mode: max
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: winner_preferred
        patience: 25
        mode: max
        verbose: true

model:
  model_name: kaiyuy/leandojo-lean3-tacgen-byt5-small
  lr: 1e-6
  warmup_steps: 200
  beta: 0.1

data:
  batch_size: 1  # effective_batch_size == batch_size * accumulate_grad_batches * devices
  eval_batch_size: 4
  max_seq_len: 2300
  num_workers: 0