# @package _global_
defaults:
  - end_to_end_defaults
  - env_config/leandojo_minif2f
  - tac_model/diversity
  - search_model/bestfs

exp_config:
  name: before_env_filter
  experiment: minif2f

logging_config:
  project: minif2f
  offline: false

tac_model:
  gpu_per_process: 0.225
  cpu_per_process: 0.125

