# @package _global_
defaults:
  - end_to_end_defaults
  - env_config/lean4_env
  - tac_model/internlm
  - search_model/dpp_critic

exp_config:
  name: dpp_critic_conditional
  experiment: internlm


logging_config:
  project: internlm_test
  offline: false


