# @package _global_
defaults:
  - end_to_end_defaults
  - env_config/leandojo_minif2f
  - tac_model/diversity
  - search_model/bestfs

exp_config:
  name: error_only
  experiment: minif2f

logging_config:
  project: minif2f
  offline: false

tac_model:
  diversity_config:
    error_only: true




