# @package _global_
defaults:
  - end_to_end_defaults
  - env_config/leandojo_no_split
  - tac_model/internlm
  - search_model/bestfs

exp_config:
  name: internlm
  experiment: internlm


logging_config:
  project: minif2f_test
  offline: true


