# @package _global_
defaults:
  - /base/logging_config@_here_
  - /base/exp_config@_here_

exp_config:
  name: internlm_transition_error_score_only
  experiment: internlm_transition
#  resume: true
#  directory: runs/error_pred/combined_transition_model/2024_08_09/14_12_23

logging_config:
  project: internlm_transition
  offline: true
#  id: w7z63cra

model:
  _target_: models.end_to_end.tactic_models.internlm_transitions.model.InternLMTransitionModel
  config:
    load_ckpt: false
    emb_dim: 2048
    #    load_ckpt: true
    #    ckpt_path: runs/combined_minif2f_valid_fixed.ckpt
    #    ckpt_path: 'runs/diversity/large-single-vec-2/2024_07_15/10_57/checkpoints/last.ckpt'
    # for biased error/success distribution
    #    tac_encoder: sean-lamont/leandojo-lean3-reprover-novel-premises
    #    goal_encoder: sean-lamont/leandojo-lean3-reprover-novel-premises
    #    decoder: sean-lamont/leandojo-lean3-reprover-novel-premises
    score_weight: 1
    error_weight: 1
    max_length: 5000
    num_samples: 4
    lr: 5e-5
    warmup_steps: 200
    #    label_weights: [ 0.0005, 0.95 ]
    label_weights: [ 1.,1. ]

data_module:
  _target_: models.end_to_end.tactic_models.internlm_transitions.datamodule.InternLMTransitionDataModule
  model_name: sean-lamont/leandojo-lean3-reprover-novel-premises
  batch_size: 1 # effective_batch_size == batch_size * accumulate_grad_batches * devices
  eval_batch_size: 1
  max_seq_len: 5000
  max_output_len: 5000
  num_workers: 0
  collection: 'critic_batched_tactics'
  trace_files: runs/internlm/internlm_cg/2025_03_08/05_15_27/traces/0 # "runs/internlm/internlm_cg/2025_02_24/13_36_16/traces/0"
  replace: 'keep' # add/keep/drop files wrt the existing collection


trainer:
  accelerator: gpu
  devices: 1
  #  num_nodes: 2
  precision: bf16-mixed
  #  strategy:
  #    _target_: lightning.pytorch.strategies.DeepSpeedStrategy
  #    stage: 1
  #    offload_optimizer: false
  #    cpu_checkpointing: false
  #    logging_batch_size_per_gpu: 1

  gradient_clip_val: 1.0

  val_check_interval: 10_000


  callbacks:
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      verbose: true
      save_top_k: 1
      save_last: true
      monitor: true_pos
      mode: max
      dirpath: ${exp_config.directory}/checkpoints
      auto_insert_metric_name: true
      filename: "{epoch}-{step}-{true_pos:.2f}"
      enable_version_counter: false

