# @package _global_
defaults:
  - /base/logging_config@_here_
  - /base/exp_config@_here_

exp_config:
  name: all_tokens
  experiment: error_pred
  resume: true
  directory: "runs/error_pred/all_tokens/2024_09_23/11_20_45"
#  directory: runs/error_pred/all_tokens/2024_09_09/10_35_28
#  runs/error_pred/combined_transition_model/2024_08_09/14_12_23

logging_config:
  project: error_pred
  offline: false
  id: hnxrrzsc
#  id: vc5xjsah
#  id: 63o7xawk
#  id: g40re013
#  id: socdvm9k

model:
  _target_: models.end_to_end.tactic_models.error_pred.all_tokens.AllTokenModel
  config:
    load_ckpt: false
#    load_ckpt: true
#    ckpt_path: runs/combined_minif2f_valid_fixed.ckpt
#    ckpt_path: 'runs/diversity/large-single-vec-2/2024_07_15/10_57/checkpoints/last.ckpt'
    error_weight: 1
    time_weight: 1
    # for biased error/success distribution
    label_weights: [ 0.25, 0.75 ]
    tac_encoder: sean-lamont/leandojo-lean3-reprover-novel-premises
    goal_encoder: sean-lamont/leandojo-lean3-reprover-novel-premises
    decoder: sean-lamont/leandojo-lean3-reprover-novel-premises
    max_length: 2500
    num_samples: 4
    lr: 5e-5
    warmup_steps: 200

data_module:
  _target_: models.end_to_end.tactic_models.error_pred.datamodule.ErrorPredDataModule
  model_name: sean-lamont/leandojo-lean3-reprover-novel-premises
  batch_size: 1 # effective_batch_size == batch_size * accumulate_grad_batches * devices
  eval_batch_size: 1
  max_seq_len: 1650
  num_workers: 0
  collection: 'minif2f_transitions'
  trace_files: null #'runs/minif2f_test_bestfs/0' #runs/minif2f/minif2f_bestfs/2024_07_31/16_28_47/traces/0'
  replace: 'keep' # add/keep/drop files wrt the existing collection


trainer:
  accelerator: gpu
  devices: 1
  #  num_nodes: 2
  precision: bf16-mixed
  strategy:
    _target_: lightning.pytorch.strategies.DeepSpeedStrategy
    stage: 1
    offload_optimizer: false
    cpu_checkpointing: false
    logging_batch_size_per_gpu: 1

  gradient_clip_val: 1.0

#  val_check_interval: 20_000
#  limit_val_batches: 1000


  callbacks:
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      verbose: true
      save_top_k: 3
      save_last: true
      monitor: top4_acc_val
      mode: max
      dirpath: ${exp_config.directory}/checkpoints
      auto_insert_metric_name: true
      filename: "{epoch}-{step}-{top4_acc_val:.2f}"
      enable_version_counter: false

