# @package _global_
defaults:
  - mizar
  - /data_type/gnn@_here_

exp_config:
    name: gnn

experiment:
  goal_embedding_module:
    _target_: models.embedding_models.gnn.formula_net.formula_net.FormulaNetEdges
    input_shape: ${data_config.vocab_size}
    embedding_dim: 128
    num_iterations: 4
    batch_norm: true

  premise_embedding_module:
    _target_: models.embedding_models.gnn.formula_net.formula_net.FormulaNetEdges
    input_shape: ${data_config.vocab_size}
    embedding_dim: 128
    num_iterations: 4
    batch_norm: true
