# @package _global_
defaults:
  - tactic_zero
  - /data_type/gnn@_here_

exp_config:
  name: tacticzero_gnn

model_config:
  model_type: formula-net-edges
  model_attributes:
    embedding_dim: 256
    gnn_layers: 2
    batch_norm: False

# load pretrained encoder after running on HOL4 premise selection task
pretrain: false
pretrain_ckpt: ""