# @package _global_
defaults:
  - tactic_zero

logging_config:
  offline: true

max_steps: 50
data_config:
  type: 'fixed'
  data_options:
    filter: []

exp_config:
  name: full_fringe_50_step

model_config:
  # original autoencoder used in TacticZero
  model_type: 'fixed_autoencoder'
  model_attributes:
    # default path for the original encoder
    checkpoint_path: 'models/TacticZero/pretrained_autoencoder'
    embedding_dim: 256