# @package _global_
defaults:
  - holist_supervised
  - /data_type/gnn@_here_

exp_config:
  name: gnn_small

experiment:
  goal_embedding_module:
    _target_: models.embedding_models.holist_models.gnn.gnn_encoder.GNNEncoder
    input_shape: ${data_config.vocab_size}
    embedding_dim: 128
    num_iterations: 12
    max_edges: 3
    dropout: 0.2

  premise_embedding_module:
    _target_: models.embedding_models.holist_models.gnn.gnn_encoder.GNNEncoder
    input_shape: ${data_config.vocab_size}
    embedding_dim: 128
    num_iterations: 12
    max_edges: 3
    dropout: 0.2