# @package _global_
defaults:
  - holist_supervised
  - /data_type/sat@_here_

exp_config:
  name: sat

model:
  goal_embedding_module:
    _target_: models.embedding_models.holist_models.sat.models.GraphTransformer
    input_shape: ${data_config.vocab_size}
    num_class: 2
    batch_norm: true
    d_model: 128
    dim_feedforward: 256
    num_heads: 4
    num_layers: 4
    in_embed: True
    se: 'gnn-encoder'
    gnn_type: gcn
    abs_pe: false
    use_edge_attr: true
    num_edge_features: 200
    global_pool: 'mean'
    dropout: 0.2
    gnn_layers: 1
    small_inner: false

  premise_embedding_module:
    _target_: models.embedding_models.holist_models.sat.models.GraphTransformer
    input_shape: ${data_config.vocab_size}
    num_class: 2
    batch_norm: true
    d_model: 128
    dim_feedforward: 256
    num_heads: 4
    num_layers: 4
    in_embed: True
    se: 'gnn-encoder'
    gnn_type: gcn
    abs_pe: false
    use_edge_attr: true
    num_edge_features: 3
    global_pool: 'mean'
    dropout: 0.2
    gnn_layers: 1
    small_inner: false
    abs_pe_dim: 256