# @package _global_
defaults:
  - leanstep
  - /data_type/ensemble@_here_

exp_config:
  name: ensemble

model:
  goal_embedding_module:
    _target_: models.embedding_models.ensemble.ensemble.EnsembleEmbedder
    d_model: 256
    dropout: 0.
    gnn_model:
      _target_: models.embedding_models.gnn.formula_net.formula_net.FormulaNetEdges
      embedding_dim: 256
      batch_norm: true
      num_iterations: 2
      max_edges: 200
      # input_shape passed in from experiment config
      input_shape: ${data_config.vocab_size}

    transformer_model:
      _target_: models.embedding_models.transformer.transformer_encoder_model.TransformerWrapper
      ntoken: ${data_config.vocab_size}
      d_model: 256
      nhead: 4
      nlayers: 4
      dropout: 0.
      d_hid: 256
      small_inner: false
      max_len: ${data_config.attributes.max_len}

  premise_embedding_module:
    _target_: models.embedding_models.ensemble.ensemble.EnsembleEmbedder
    d_model: 256
    dropout: 0.
    gnn_model:
      _target_: models.embedding_models.gnn.formula_net.formula_net.FormulaNetEdges
      embedding_dim: 256
      batch_norm: true
      num_iterations: 2
      max_edges: 200
      # input_shape passed in from experiment config
      input_shape: ${data_config.vocab_size}

    transformer_model:
      _target_: models.embedding_models.transformer.transformer_encoder_model.TransformerWrapper
      ntoken: ${data_config.vocab_size}
      d_model: 256
      nhead: 4
      nlayers: 4
      dropout: 0.
      d_hid: 256
      small_inner: false
      max_len: ${data_config.attributes.max_len}