# @package _global_
defaults:
  - leanstep
  - /data_type/ensemble@_here_

exp_config:
  name: ensemble
#  resume: True
#  directory: 'experiments/runs/premise_selection/2023_08_11/ensemble_15_16_28'

model_config:
  model_type: ensemble
  model_attributes:
    batch_norm: True
    gnn_layers: 2
    dropout: 0.
    embedding_dim: 256
    num_layers: 4
    num_heads: 4
    dim_feedforward: 256
    max_len: 1024

#logging_config:
#  id: 'kex3q0rs'