# @package _global_
defaults:
  - leanstep
  - /data_type/gnn@_here_

exp_config:
  name: bag_of_words

experiment:
  goal_embedding_module:
    _target_: models.embedding_models.gnn.formula_net.formula_net.FormulaNetEdges
    input_shape: ${data_config.vocab_size}
    embedding_dim: 128
    num_iterations: 0
    batch_norm: true

  premise_embedding_module:
    _target_: models.embedding_models.gnn.formula_net.formula_net.FormulaNetEdges
    input_shape: ${data_config.vocab_size}
    embedding_dim: 128
    num_iterations: 0
    batch_norm: true
