defaults:
  - /premise_selection/premise_selection@_here_

data_config:
  vocab_size: 32700
  data_options:
    dict_in_memory: False
    db: 'leanstep_premise_selection'

logging_config:
  project: leanstep_premise_selection
