program: experiments.premise_selection_wandb
name: sat
description: SAT MIZAR40
project: mizar40

method: bayes
metric:
  goal: maximize
  name: acc
parameters:
  model_config.model_attributes.num_layers:
    values: [4,2]
  model_config.model_attributes.se:
    values: ['formula-net','gcn']
  model_config.model_attributes.num_heads:
    values: [4]
  model_config.model_attributes.embedding_dim:
    values: [128]

#early_terminate:
#  type: hyperband
#  min_iter: 3

command:
  - ${env}
  - ${interpreter}
  - '-m'
  - ${program}
  - '--config-name=mizar_sat_full'
  - ${args_no_hyphens}
