defaults:
  - /base/data_config@_here_
  - /base/logging_config@_here_
  - /base/exp_config@_here_

exp_config:
  experiment: premise_selection_test

trainer:
  enable_progress_bar: true
  log_every_n_steps: 500
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  strategy:
    _target_: lightning.pytorch.strategies.DeepSpeedStrategy
    stage: 2
    offload_optimizer: false
    cpu_checkpointing: false
    logging_batch_size_per_gpu: 1
  gradient_clip_val: 1.0
  max_epochs: 10
  val_check_interval: 2048
#  limit_val_batches: 0.0
  callbacks:
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      verbose: true
      save_top_k: 3
      save_last: true
      monitor: acc
      mode: max
      dirpath: ${exp_config.directory}/checkpoints
      auto_insert_metric_name: true
      filename: "{epoch}-{acc}"

experiment:
  _target_: experiments.premise_selection.premise_selection.PremiseSelection
  goal_embedding_module:
    input_shape: ${data_config.vocab_size}
  premise_embedding_module:
    input_shape: ${data_config.vocab_size}
  classifier:
    _target_: models.embedding_models.gnn.formula_net.formula_net.BinaryClassifier
    input_shape: ${..premise_embedding_module.embedding_dim}
  lr: 1e-4
  batch_size: 32

data_module:
  _target_: experiments.premise_selection.datamodule.PremiseDataModule
  config: ${data_config}


      