seed_everything: 3407  # https://arxiv.org/abs/2109.08203
trainer:
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  strategy:
    class_path: pytorch_lightning.strategies.DeepSpeedStrategy
    init_args:
      stage: 2
      offload_optimizer: false
      cpu_checkpointing: false
  gradient_clip_val: 1.0
  max_steps: 500000
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  # need this to reload ray dataloader
  reload_dataloaders_every_n_epochs: 1
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        verbose: true
        save_top_k: 1
        save_last: true
        monitor: val_score
#        monitor: val_acc
        mode: min
#        mode: max
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 3
        verbose: true
        monitor: val_score
        # monitor: val_acc
        mode: min
#        mode: max
model:
  model_name: kaiyuy/leandojo-lean3-tacgen-byt5-small
  lr: 5e-4
  warmup_steps: 200
  bucket_toks: ['<extra_id_1>', '<extra_id_2>', '<extra_id_3>', '<extra_id_4>','<extra_id_5>','<extra_id_6>',
  '<extra_id_7>','<extra_id_8>','<extra_id_9>','<extra_id_10>', <extra_id_11>]


data:
  batch_size: 2  # effective_batch_size == batch_size * accumulate_grad_batches * devices
  eval_batch_size: 4
  max_seq_len: 2300
  num_workers: 2
  critic_tok: '<extra_id_0>'
  bucket_toks: ['<extra_id_1>', '<extra_id_2>', '<extra_id_3>', '<extra_id_4>','<extra_id_5>','<extra_id_6>',
                '<extra_id_7>','<extra_id_8>','<extra_id_9>','<extra_id_10>', <extra_id_11>]